//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYS_Blanket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CYS_Blanket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.12.0;Data Source=&quot;C:\Users\Kyle work\source\repos\CYS-Blanket\CYS-Blanket\CYS_Blanket_ENVIRONMENT.accdb&quot;;Persist Security Info=True.
        /// </summary>
        internal static string DBConnectionString {
            get {
                return ResourceManager.GetString("DBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.12.0;Data Source=&quot;C:\Users\Kyle work\source\repos\CYS-Blanket\CYS-Blanket\CYS_Blanket_DEV.accdb&quot;;Persist Security Info=True.
        /// </summary>
        internal static string DevDBConnectionString {
            get {
                return ResourceManager.GetString("DevDBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.12.0;Data Source=&quot;C:\Users\Kyle work\source\repos\CYS-Blanket\CYS-Blanket\CYS_Blanket_PROD.accdb&quot;;Persist Security Info=True.
        /// </summary>
        internal static string ProdDBConnectionString {
            get {
                return ResourceManager.GetString("ProdDBConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.12.0;Data Source=&quot;C:\Users\Kyle work\source\repos\CYS-Blanket\CYS-Blanket\CYS_Blanket_QA.accdb&quot;;Persist Security Info=True.
        /// </summary>
        internal static string QADBConnectionString {
            get {
                return ResourceManager.GetString("QADBConnectionString", resourceCulture);
            }
        }
    }
}
